# Generated by Django 4.2.7 on 2024-07-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0003_uploadfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalreport',
            name='animal_type',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='animalreport',
            name='priority_type',
            field=models.CharField(max_length=20),
        ),
    ]
