# Generated by Django 5.0 on 2024-02-03 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('photo', models.ImageField(upload_to='animal_photos/')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField()),
                ('animal_type', models.CharField(choices=[('Pet', 'Pet'), ('Stray', 'Stray')], max_length=5)),
                ('priority_type', models.CharField(choices=[('Emergency', 'Emergency'), ('Urgent', 'Urgent'), ('Not-Urgent', 'Not-Urgent')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ngoForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngoUserName', models.CharField(max_length=20)),
                ('ngoPhoneNumber', models.IntegerField()),
                ('ngoImage', models.ImageField(upload_to='')),
                ('ngoDesc', models.TextField()),
                ('ngoAniType', models.CharField(max_length=10)),
                ('ngoAniPriority', models.CharField(max_length=15)),
            ],
        ),
    ]
