# Generated by Django 4.2.7 on 2024-07-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0004_alter_animalreport_animal_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ngoForm',
        ),
        migrations.RenameField(
            model_name='animalreport',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='animalreport',
            old_name='phone_number',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='animalreport',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='animalreport',
            name='priority_type',
        ),
        migrations.AddField(
            model_name='animalreport',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='animalreport',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='animalreport',
            name='priority',
            field=models.CharField(choices=[('emergency', 'Emergency'), ('urgent', 'Urgent'), ('not_urgent', 'Not Urgent')], default='not_urgent', max_length=15),
        ),
        migrations.AlterField(
            model_name='animalreport',
            name='animal_type',
            field=models.CharField(choices=[('pet', 'Pet'), ('stray', 'Stray')], max_length=10),
        ),
        migrations.AlterField(
            model_name='animalreport',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=200),
        ),
        migrations.AlterField(
            model_name='animalreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
